= Languages

Many programming languages are available to choose from, each with their own
advantages and disadvantages. This section (to be expanded!) contains a short
comparison of some popular or interesting languages, as well as some in-depth
guides.

C::
One of the oldest programming languages still in use is `C`. It very widespread,
and included in almost all Linux distributions and macOS. Many languages have a
small core implemented in `C`, and it is often used as a common interface
between toolkits. However, it lacks some of the useful features of more modern
languages. It is a compiled, imperative, statically typed programming language.

Python::
https://python.org[Python] is an interpreted, dynamically typed programming language.
It is largely imperative, but also has some functional programming features.
Alternative implementations which are compiled on-the-fly for performance, such
as https://pypy.org[PyPy], exist too.

Haskell::
https://haskell.org[Haskell] is a compiled, statically typed, functional programming
language. The web-site includes a simple haskell interpreter.

Rust::
https://rust-lang.org[Rust] is a compiled, statically typed programming language. It is
largely imperative, but has good support for functional programming styles.

Scheme::
Scheme is a dynamically typed, interpreted programming language. It is a
functional programming language known for its minimalism.

:leveloffset: +1

include::python/index.adoc[]

include::C/index.adoc[]

include::nix/index.adoc[]

:leveloffset: -1
